# Generated by Django 5.0.6 on 2024-06-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compny_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'IT'), ('None It', 'None It'), ('Mobile phones', 'Mobile Phones')], max_length=50)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('actived', models.BooleanField(default=True)),
            ],
        ),
    ]
